In [1]:
from google.colab import files
supermarket=files.upload()

Saving Supermarket_sales (1).csv to Supermarket_sales (1) (1).csv


In [8]:
import pandas as pd
dataframe=pd.read_csv("Supermarket_sales (1).csv")
print(dataframe)

       No    InvoiceID Branch       City Customertype  Gender  \
0       1  750-67-8428      A     Yangon       Member  Female   
1       2  226-31-3081      C  Naypyitaw       Normal  Female   
2       3  631-41-3108      A     Yangon       Normal    Male   
3       4  123-19-1176      A     Yangon       Member    Male   
4       5  373-73-7910      A     Yangon       Normal    Male   
..    ...          ...    ...        ...          ...     ...   
995   996  233-67-5758      C  Naypyitaw       Normal    Male   
996   997  303-96-2227      B   Mandalay       Normal  Female   
997   998  727-02-1313      A     Yangon       Member    Male   
998   999  347-56-2442      A     Yangon       Normal    Male   
999  1000  849-09-3807      A     Yangon       Member  Female   

                Productline  Unitprice  Quantity      Tax      Total  \
0         Health and beauty      74.69         7  26.1415   548.9715   
1    Electronic accessories      15.28         5   3.8200    80.2200   
2  

In [9]:
print(dataframe.head(10))

   No    InvoiceID Branch       City Customertype  Gender  \
0   1  750-67-8428      A     Yangon       Member  Female   
1   2  226-31-3081      C  Naypyitaw       Normal  Female   
2   3  631-41-3108      A     Yangon       Normal    Male   
3   4  123-19-1176      A     Yangon       Member    Male   
4   5  373-73-7910      A     Yangon       Normal    Male   
5   6  699-14-3026      C  Naypyitaw       Normal    Male   
6   7  355-53-5943      A     Yangon       Member  Female   
7   8  315-22-5665      C  Naypyitaw       Normal  Female   
8   9  665-32-9167      A     Yangon       Member  Female   
9  10  692-92-5582      B   Mandalay       Member  Female   

              Productline  Unitprice  Quantity      Tax     Total       Date  \
0       Health and beauty      74.69         7  26.1415  548.9715   1/5/2019   
1  Electronic accessories      15.28         5   3.8200   80.2200   3/8/2019   
2      Home and lifestyle      46.33         7  16.2155  340.5255   3/3/2019   
3       

In [11]:
print(dataframe.tail(8))

       No    InvoiceID Branch       City Customertype  Gender  \
992   993  745-74-0715      A     Yangon       Normal    Male   
993   994  690-01-6631      B   Mandalay       Normal    Male   
994   995  652-49-6720      C  Naypyitaw       Member  Female   
995   996  233-67-5758      C  Naypyitaw       Normal    Male   
996   997  303-96-2227      B   Mandalay       Normal  Female   
997   998  727-02-1313      A     Yangon       Member    Male   
998   999  347-56-2442      A     Yangon       Normal    Male   
999  1000  849-09-3807      A     Yangon       Member  Female   

                Productline  Unitprice  Quantity      Tax      Total  \
992  Electronic accessories      58.03         2   5.8030   121.8630   
993     Fashion accessories      17.49        10   8.7450   183.6450   
994  Electronic accessories      60.95         1   3.0475    63.9975   
995       Health and beauty      40.35         1   2.0175    42.3675   
996      Home and lifestyle      97.38        10  48.6

In [12]:
dataframe.loc[1]

No                                              2
InvoiceID                             226-31-3081
Branch                                          C
City                                    Naypyitaw
Customertype                               Normal
Gender                                     Female
Productline                Electronic accessories
Unitprice                                   15.28
Quantity                                        5
Tax                                          3.82
Total                                       80.22
Date                                     3/8/2019
Time                                        10:29
Payment                                      Cash
cogs                                         76.4
gross_margin_percentage                  4.761905
gross_iincome                                3.82
Rating                                        9.6
Name: 1, dtype: object

In [15]:
dataframe[['City','Branch']]

City Branch
0       Yangon      A
1    Naypyitaw      C
2       Yangon      A
3       Yangon      A
4       Yangon      A
..         ...    ...
995  Naypyitaw      C
996   Mandalay      B
997     Yangon      A
998     Yangon      A
999     Yangon      A

[1000 rows x 2 columns]

In [29]:
dataframe=dataframe.drop(["gross_margin_percentage"],axis=1)
dataframe.head(4)

No    InvoiceID Branch       City Customertype  Gender  \
0   1  750-67-8428      A     Yangon       Member  Female   
1   2  226-31-3081      C  Naypyitaw       Normal  Female   
2   3  631-41-3108      A     Yangon       Normal    Male   
3   4  123-19-1176      A     Yangon       Member    Male   

              Productline  Unitprice  Quantity     Total       Date   Time  \
0       Health and beauty      74.69         7  548.9715   1/5/2019  13:08   
1  Electronic accessories      15.28         5   80.2200   3/8/2019  10:29   
2      Home and lifestyle      46.33         7  340.5255   3/3/2019  13:23   
3       Health and beauty      58.22         8  489.0480  1/27/2019  20:33   

       Payment    cogs  gross_iincome  Rating  
0      Ewallet  522.83        26.1415     9.1  
1         Cash   76.40         3.8200     9.6  
2  Credit card  324.31        16.2155     7.4  
3      Ewallet  465.76        23.2880     8.4

In [41]:
max_price=dataframe.Unitprice.max()
print(max_price)

99.96


In [42]:
min_price=dataframe.Unitprice.min()
print(min_price)

10.08


In [44]:
dataframe.loc[dataframe["Customertype"]=="Normal"]

No    InvoiceID Branch       City Customertype  Gender  \
1      2  226-31-3081      C  Naypyitaw       Normal  Female   
2      3  631-41-3108      A     Yangon       Normal    Male   
4      5  373-73-7910      A     Yangon       Normal    Male   
5      6  699-14-3026      C  Naypyitaw       Normal    Male   
7      8  315-22-5665      C  Naypyitaw       Normal  Female   
..   ...          ...    ...        ...          ...     ...   
992  993  745-74-0715      A     Yangon       Normal    Male   
993  994  690-01-6631      B   Mandalay       Normal    Male   
995  996  233-67-5758      C  Naypyitaw       Normal    Male   
996  997  303-96-2227      B   Mandalay       Normal  Female   
998  999  347-56-2442      A     Yangon       Normal    Male   

                Productline  Unitprice  Quantity      Total       Date   Time  \
1    Electronic accessories      15.28         5    80.2200   3/8/2019  10:29   
2        Home and lifestyle      46.33         7   340.5255   3/3/2019  13:23   
4         Sports and travel      86.31         7   634.3785   2/8/2019  10:37   
5    Electronic accessories      85.39         7   627.6165  3/25/2019  18:30   
7        Home and lifestyle      73.56        10   772.3800  2/24/2019  11:38   
..                      ...        ...       ...        ...        ...    ...   
992  Electronic accessories      58.03         2   121.8630  3/10/2019  20:46   
993     Fashion accessories      17.49        10   183.6450  2/22/2019  18:35   
995       Health and beauty      40.35         1    42.3675  1/29/2019  13:46   
996      Home and lifestyle      97.38        10  1022.4900   3/2/2019  17:16   
998      Home and lifestyle      65.82         1    69.1110  2/22/2019  15:33   

         Payment    cogs  gross_iincome  Rating  
1           Cash   76.40         3.8200     9.6  
2    Credit card  324.31        16.2155     7.4  
4        Ewallet  604.17        30.2085     5.3  
5        Ewallet  597.73        29.8865     4.1  
7        Ewallet  735.60        36.7800     8.0  
..           ...     ...            ...     ...  
992      Ewallet  116.06         5.8030     8.8  
993      Ewallet  174.90         8.7450     6.6  
995      Ewallet   40.35         2.0175     6.2  
996      Ewallet  973.80        48.6900     4.4  
998         Cash   65.82         3.2910     4.1  

[499 rows x 16 columns]

In [45]:
dataframe.loc[dataframe["Gender"]=="Male"]

No    InvoiceID Branch       City Customertype Gender  \
2      3  631-41-3108      A     Yangon       Normal   Male   
3      4  123-19-1176      A     Yangon       Member   Male   
4      5  373-73-7910      A     Yangon       Normal   Male   
5      6  699-14-3026      C  Naypyitaw       Normal   Male   
11    12  529-56-3974      B   Mandalay       Member   Male   
..   ...          ...    ...        ...          ...    ...   
992  993  745-74-0715      A     Yangon       Normal   Male   
993  994  690-01-6631      B   Mandalay       Normal   Male   
995  996  233-67-5758      C  Naypyitaw       Normal   Male   
997  998  727-02-1313      A     Yangon       Member   Male   
998  999  347-56-2442      A     Yangon       Normal   Male   

                Productline  Unitprice  Quantity     Total       Date   Time  \
2        Home and lifestyle      46.33         7  340.5255   3/3/2019  13:23   
3         Health and beauty      58.22         8  489.0480  1/27/2019  20:33   
4         Sports and travel      86.31         7  634.3785   2/8/2019  10:37   
5    Electronic accessories      85.39         7  627.6165  3/25/2019  18:30   
11   Electronic accessories      25.51         4  107.1420   3/9/2019  17:03   
..                      ...        ...       ...       ...        ...    ...   
992  Electronic accessories      58.03         2  121.8630  3/10/2019  20:46   
993     Fashion accessories      17.49        10  183.6450  2/22/2019  18:35   
995       Health and beauty      40.35         1   42.3675  1/29/2019  13:46   
997      Food and beverages      31.84         1   33.4320   2/9/2019  13:22   
998      Home and lifestyle      65.82         1   69.1110  2/22/2019  15:33   

         Payment    cogs  gross_iincome  Rating  
2    Credit card  324.31        16.2155     7.4  
3        Ewallet  465.76        23.2880     8.4  
4        Ewallet  604.17        30.2085     5.3  
5        Ewallet  597.73        29.8865     4.1  
11          Cash  102.04         5.1020     6.8  
..           ...     ...            ...     ...  
992      Ewallet  116.06         5.8030     8.8  
993      Ewallet  174.90         8.7450     6.6  
995      Ewallet   40.35         2.0175     6.2  
997         Cash   31.84         1.5920     7.7  
998         Cash   65.82         3.2910     4.1  

[499 rows x 16 columns]

In [46]:
import numpy as np

In [48]:
student_marks_BA=[12,14,10]
marksarray=np.array(student_marks_BA)
print(marksarray)

[12 14 10]


In [49]:
student_marks_BA=[[12,14,10],[15,19,20],[11,15,19]]
marksarray=np.array(student_marks_BA)
print(marksarray)

[[12 14 10]
 [15 19 20]
 [11 15 19]]


In [51]:
student_marks_BA=[[12,14],[19,20],[15,19],[17,13]]
marksarray=np.array(student_marks_BA)
print(marksarray)
marksarray.shape

[[12 14]
 [19 20]
 [15 19]
 [17 13]]


(4, 2)

In [52]:
values1=np.arange(20)
print(values1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [53]:
values2=np.arange(50,60)
print(values2)

[50 51 52 53 54 55 56 57 58 59]


In [54]:
value3=np.arange(70,100,3)
print(value3)

[70 73 76 79 82 85 88 91 94 97]


In [57]:
zeroarray = np.zeros((2,6))
print(zeroarray)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [59]:
onesarray = np.ones((4,2))
print(onesarray)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [60]:
identityarray=np.eye(5)
print(identityarray)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [61]:
identityarray=np.eye(5,2)
print(identityarray)

[[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [62]:
len(zeroarray)

2

In [63]:
len(onesarray)

4

In [66]:
firstarray=np.array([[20,30,40],[4,6,8],[10,15,20],[1,3,5]])
print(firstarray.shape)
secondarray=firstarray.reshape(3,4)
print(secondarray)

(4, 3)
[[20 30 40  4]
 [ 6  8 10 15]
 [20  1  3  5]]


In [67]:
values=np.random.randint(1,3,5)
print(values)

[2 1 2 2 1]


In [68]:
values=np.random.randint(44,88,6)
print(values)

[68 58 48 83 69 82]


In [71]:
values = np.random.randint(25,50,(4,3))
print(values)

[[29 37 35]
 [35 43 46]
 [48 29 29]
 [40 25 28]]
